#ifndef _MALFUNC_H_
#define _MALFUNC_H_

enum {
	////////////////////////////////////////////////////////////////
	// Alle diese Fehler werden z. Zt. in 'sensors_signal_server.c'/
	// gelöscht. Bei Neuverwendung beachten!!                   ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_1_1_SIGNAL_EXCEEDS_1 = 211,    ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_1_2_SIGNAL_EXCEEDS_1 = 212,    ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_1_3_SIGNAL_EXCEEDS_1 = 213,    ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_2_1_SIGNAL_EXCEEDS_1 = 221,    ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_2_2_SIGNAL_EXCEEDS_1 = 222,    ////
	MALFUNC_ULTIMATE_SENSOR_NDIR_2_3_SIGNAL_EXCEEDS_1 = 223,    ////
	MALFUNC_ULTIMATE_SENSOR_TNB_SIGNAL_EXCEEDS_1      = 231,    ////
	MALFUNC_ULTIMATE_SENSOR_ZIROX_COLD                = 240,    ////
	MALFUNC_ULTIMATE_SENSOR_ZIROX_SIGNAL_EXCEEDS_1    = 241,    ////
	////////////////////////////////////////////////////////////////
	////////////////////////////////////////////////////////////////

	MALFUNC_ULTRA_MEASUREMENT_MEASUREMENT_PROCESS     = 1300,
	MALFUNC_ULTRA_XY_SYSTEM                           = 1700,
	MALFUNC_ULTRA_X_AXIS_MOVEMENT                     = 1710,
	MALFUNC_ULTRA_Y_AXIS_MOVEMENT                     = 1720,
	MALFUNC_ULTRA_Z_AXIS_MOVEMENT                     = 1730,
	MALFUNC_ULTRA_Z_AXIS_VOLUME                       = 1732,
	MALFUNC_ULTIMATE_FURNACE_CAN                      = 1805,
	MALFUNC_ULTIMATE_TICPORT_CAN                      = 1806,
	MALFUNC_ULTIMATE_FURNACE_DEAD                     = 1810,
	MALFUNC_ULTIMATE_HUMIDITY_LIMIT_EXCEEDED          = 1815,
	MALFUNC_ULTIMATE_HUMIDITY_CABLE_BROKEN            = 1816,
	MALFUNC_ULTIMATE_FURNACE_COLD                     = 1820,
	MALFUNC_ULTIMATE_FURNACE_BIT_FAIL                 = 1821,
	MALFUNC_ULTIMATE_TICPORT                          = 1822,
	MALFUNC_ULTIMATE_FURNACE_COOLER_COLD              = 1825,
	MALFUNC_ULTIMATE_AIRFLOW_MONITORING               = 1830,
	MALFUNC_ULTIMATE_HUMIDITY_LIMIT_EXCEEDED_         = 1831,
	MALFUNC_ANY_PRESSURE_HIGH_300                     = 1832,
	MALFUNC_ANY_PRESSURE_HIGH_600                     = 1833,
	MALFUNC_ULTIMATE_PRESSURE_CABLE_BROKEN            = 1834,
	MALFUNC_ULTIMATE_AIRFLOW_CARRIER_GASFLOW_IN       = 1835,
	MALFUNC_ULTIMATE_AIRFLOW_CARRIER_GASFLOW_OUT_TC   = 1836,
	MALFUNC_ULTIMATE_AIRFLOW_CARRIER_GASFLOW_OUT_TIC  = 1837,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_1               = 1841,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_2               = 1842,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_3               = 1843,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_4               = 1844,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_5               = 1845,
	MALFUNC_ULTIMATE_STREAM_NO_SAMPLE_6               = 1846,
	MALFUNC_ULTRA_MEASUREMENT_CALIBRATION_PROCESS     = 1920,
	MALFUNC_ULTRA_HOLD_REPAETLY_NOT_FOUND             = 2001,
	MALFUNC_ULTRA_RINSING_REPAETLY                    = 2011,
	MALFUNC_ULTRA_RINSING_DRAIN_NOT_FOUND             = 2012,
	MALFUNC_ULTRA_AXISHOLD_PROCESS                    = 2030,
	MALFUNC_ULTRA_INJECTIONTIC_PROCESS                = 2040,
	MALFUNC_ULTRA_SAMPLING_PROCESS                    = 2050,
	MALFUNC_ULTRA_SAMPLING_VOLUME                     = 2051,
	MALFUNC_ULTRA_MEASUREMENT_TIC                     = 2070,  //
	MALFUNC_ULTRA_MEASUREMENT_TIC_                    = 2080,  // Wo ist der Unterschied?
	MALFUNC_ULTRA_DILUTION_SAMPLE_FAIL                = 2107,
	MALFUNC_ULTRA_INJECTION_UNKNOWN                   = 2330
};

#endif
